#!/bin/bash

set -e

echo -e "\033[36;1mRunning debug tests:\033[0m"
cargo test

echo -e "\033[36;1mRunning debug/force-enabled tests:\033[0m"
cargo test --features force-enabled

echo -e "\033[36;1mRunning release tests:\033[0m"
cargo test --release

echo -e "\033[36;1mRunning release/force-enabled tests:\033[0m"
cargo test --release --features force-enabled

echo -e "\033[36;1mRunning rustfmt:\033[0m"
cargo fmt -- --check

echo -e "\033[36;1mRunning clippy:\033[0m"
cargo clippy -- -D clippy::all

